/**
 * Global configuration and constants for the Headstart Add-on.
 */

const CONFIG = {
  BATCH_DAYS: 3,
  GOOGLE_BLUE: "#1a73e8",
  GOOGLE_GREY: "#5f6368",
  CALENDAR_NAME: "Headstart",
  TAG_PARENT_ID: "HEADSTART_PARENT_ID",
  TAG_PARENT_CAL_ID: "HEADSTART_PARENT_CAL_ID",
  TAG_PARENT_START_MS: "HEADSTART_PARENT_START_MS",
  TAG_PARENT_END_MS: "HEADSTART_PARENT_END_MS",
  TAG_BUFFER_MINUTES: "HEADSTART_BUFFER_MINUTES",
  TAG_CONFERENCE_FINGERPRINT: "HEADSTART_CONFERENCE_FINGERPRINT"
}
